### ISSUE TITLE
Use less instead of scss

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1003]
**Is your feature request related to a problem? Please describe.**
For `ant-design` we need to support `less` in order to override the theme variables and to only import the styling files that are used by the components we are using. 

We are currently using `scss` files for our styling, but having the need to support both `scss` and `less` means that we need two css pre-processors and webpack style loaders to build the app (I became more aware of that in this PR #1000, for example in the PR to support our `scss` files I needed to add `sass` (pre-processor), `sass-loader` (webpack loader) and `@neutrinojs/style-loader` (neutrino package to support more than two styling pre-processor)).

If we change our styling files to `less` we could also directly use any ant design theme variables! (specified here https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less) Which means we can more easily stay consistent with `ant-design` styling and use directly the colors, margins, borders, shadows, .... from `ant-design`, which is something I wanted to do in #1002, but can't because we're not using the same css pre-processor.

**Describe the solution you'd like**
Switch our styling files to `less` (just tried locally and I just needed to rename all the styling files from `.scss` to `.less`). Again, this would bring conflicts to people having brought changes to the styling files, or maybe not since it is just file renames.

What do you think @dynamic11 and @MohamedRadwan?

**Comment by mo-5** [comment]
Would we need to make changes to the style files or just change the .scss to .less ? if we only need to change the file type I don't think it will be a big change.

**Comment by BenJeau** [comment]
We only need to change the extensions and the variables I created in the variables.scss from `$var: blue` to `@var: blue`, but thats just in the global styling files
