### ISSUE TITLE
IE is not working (because of arrow functions)

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1017]
**Describe the bug**
The application is not working on IE

**To Reproduce**
1. Go on IE and see the application favicon forever

**Expected behavior**
The application to work on IE

**Screenshots**
![image](https://user-images.githubusercontent.com/22248828/97451384-13f32000-190a-11eb-9387-8aa12cc3fe97.png)

**Additional context**
I think this is related to the terser uglifier (just need to modify the arrow config https://github.com/terser/terser#compress-options)

**Comment by BenJeau** [comment]
not sure if I'll be able to touch this, this week @dynamic11 feel free to takeover - I know think its somehow related to neutrino, https://neutrinojs.org/packages/react/#polyfills, or maybe this https://neutrinojs.org/packages/web/#targets

**Comment by MenaMachado** [comment]
It doesn't seem to be working in Edge either

**Comment by BenJeau** [comment]
Oh really, that's bizarre, I will take a deeper look

**Comment by BenJeau** [comment]
@MenaMachado I'm done my hours for the week (so I won't be able to touch this issue). Is prod something we want to accomplish this week? If so, I can work a bit more and work less for the following week

**Comment by MenaMachado** [comment]
Next week is fine

On Nov 4, 2020, at 6:23 PM, Benoît Jeaurond <notifications@github.com> wrote:

﻿

@MenaMachado<https://github.com/MenaMachado> I'm done my hours for the week (so I won't be able to touch this issue). Is prod something we want to accomplish this week? If so, I can work a bit more and work less for the following week
