### ISSUE TITLE
Google website analysis

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1020]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/97469817-33477880-191d-11eb-9ed5-3c46234921c4.png)
![image](https://user-images.githubusercontent.com/21133129/97469875-44908500-191d-11eb-90e5-3cf6289dd61e.png)
![image](https://user-images.githubusercontent.com/21133129/97469926-507c4700-191d-11eb-954e-0db89f7c8946.png)

**Additional context**

**Comment by BenJeau** [comment]
Unsurprisingly, keycloak is the request that takes the longest haha

**Comment by BenJeau** [comment]
Just to clarify the point of this issue, what does this tells us? Or what is actionable by us?

**Comment by mo-5** [comment]
> Just to clarify the point of this issue, what does this tells us? Or what is actionable by us?

To get someone to look into improving that score. At least bring it up to 80

**Comment by mo-5** [comment]
we can close and I will make smaller issues with more targeted tasks
