### ISSUE TITLE
Update UAT

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1025]
**Is your feature request related to a problem? Please describe.**
UAT is a month old and we should probably update it soon

**Describe the solution you'd like**
Update UAT

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mo-5** [comment]
Please let me know when this is being done so we can also move to the aws database

**Comment by mo-5** [comment]
AWS database secrets have been added to openshift. Once we update production simply change the secrets

**Comment by mo-5** [comment]
UAT is now updated
