### ISSUE TITLE
Move back to npm from yarn

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1027]
**Describe the bug**
I noticed that with npm you get warnings and errors that we wouldn't otherwise get with yarn if we don't use yarn check. 

Currently, there are some packages that have been deprecated that we need to take care of. 

Moving to npm would also mean that we won't need to run the step of installing yarn on Jenkins which possibly saves some time and we can also use a smaller node docker image that doesn't contain yarn. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BenJeau** [comment]
We should also take into consideration the benefits of yarn (parallel installation, caching of packages locally, and generation of license, if we care about that, with `yarn licenses generate-disclaimer`)

And from Jenkins logs, it seems to only take 2 seconds to install yarn
![image](https://user-images.githubusercontent.com/22248828/97587806-318bbc80-19d2-11eb-8825-eed0c3ea1baf.png)

Removing yarn from the docker image would mean using a custom docker image and not the official one from node.js, which is something I'm not sure we should do. Just saw the lts of node.js is v14.15, we should prob update them, if they don't introduce any bugs

Not saying that we shouldn't switch if its better, but we should look at both sides before switching
