### ISSUE TITLE
Disable snyk protect in Jenkins

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1036]
@MohamedRadwan Do you think we should somehow disable this in Jenkins? It takes 40sec and could save that time while linting

![image](https://user-images.githubusercontent.com/22248828/97919023-151ab780-1d25-11eb-8875-522972992c74.png)

**Comment by mo-5** [comment]
not sure where that is coming from it doesn't seem like it's in the Jenkins file

**Comment by BenJeau** [comment]
I think its magically this line somehow
https://github.com/CDH-Studio/I-Talent/blob/ce54753bb250bb88e84bbef1c945a27d6d38a86d/services/backend/package.json#L18

**Comment by BenJeau** [comment]
I'm closing this as I just saw that it only happens in my PR and snyk added this line in the package.json
![image](https://user-images.githubusercontent.com/22248828/97927075-4d74c280-1d32-11eb-8c25-c098b18ecf61.png)
