### ISSUE TITLE
Career and talent management form makes the profile and edit profile innaccesible

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1043]
**Describe the bug**
Saving anything inside that form will make the application crash when fetching data from the backend (for my profile and edit profile).

**To Reproduce**
1. Go to 'Career and talent management form'
2. Save any content
3. See error

**Expected behavior**
To not crash the application

**Screenshots**
When accessing my profile
![image](https://user-images.githubusercontent.com/22248828/98121724-a9982d80-1e7d-11eb-89e0-8dc9354cc233.png)

When accessing edit profile
![image](https://user-images.githubusercontent.com/22248828/98121692-a00ec580-1e7d-11eb-812e-7183cc880f0c.png)

**Additional context**
maybe fixed in #1013 - or is it in another PR @dynamic11?

**Comment by dynamic11** [comment]
Yea that PR should fix it. I'm going to start working on it again now

**Comment by mo-5** [comment]
![image](https://user-images.githubusercontent.com/21133129/98861316-0f168c00-2433-11eb-9598-9f6f6f81730a.png)

I think this is related to this issue. Can someone confirm so that if it is not I will open a new issue?

**Comment by BenJeau** [comment]
I think it is related to this issue, @dynamic11 can you confirm, I don't exactly remember the error that was happening in the backend. I remember fixing this issue with you last week, how is it coming along?

**Comment by mo-5** [comment]
Mena sent a message that casey is trying to show a demo but his profile is not coming up. I cant seem to be able to access his profile and this is the error the backend is giving. I am not sure which part of the form is causing this.

**Comment by BenJeau** [comment]
If this is the case, I can pull out the fix from the #1013 PR and create a seperate PR. It's only a few lines from https://github.com/CDH-Studio/I-Talent/pull/1013/commits/c1a4ef35e6925fb59b6035b428f96d918578a1da
