### ISSUE TITLE
Search functionality in categories table not working

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1046]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/98134550-e0297480-1e8c-11eb-8388-7bcc2306efcb.png)
![image](https://user-images.githubusercontent.com/21133129/98134598-eae40980-1e8c-11eb-8d32-6387ef4d84f2.png)

**Additional context**

**Comment by BenJeau** [comment]
Are you sure this is a problem in dev? I just tried it locally and on openshift, and its fine 
![image](https://user-images.githubusercontent.com/22248828/98607034-51ff2500-22b6-11eb-82ca-e14ff128fe49.png)

**Comment by mo-5** [comment]
yes, you are right. I can't reproduce it. weird. closing the issue for now.
