### ISSUE TITLE
Split profile API endpoint

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1047]
## Is your feature request related to a problem? Please describe.
The profile API endpoint is responsable for a lot of things, that endpoint is not a correct implementation of REST and feels like a custom graphQL mutation endpoint (in the way you can throw anything at and it will update, delete, or/and create entries). We should split it based on its content for the code to be cleaner, the responses to be shorter and thus faster. For example, the update and get profile endpoint has around 700-800 lines of codes each. Having it all in one endpoint also means that we have a lot of different logic for different parts of the profiles in one place, which means the code is highly coupled and that's not good. Seperating it would decouple our backend code and make more sense to new comers / maintainers.

> **Note:** this problem became more appearant as we build more and more features and cover all of the edge cases. If we don't do anything now the lines of code and complexity of the profile APIs will continue to grow. We are inherently not making it explicit what the profile endpoint can and cannot do

### Advantages
- More modularized code
- More testable code
- Faster API responses
- More conventional to the REST standard

### Disadvantages
- Need to change everywhere where we are calling the profile endpoint
- Need to make multiple API calls (whereas we are only making one now)
- Redundant code for the backend (but it makes it more testable, predictable, and divided) - just like what has been done to the options API in the summer

### What we have now (**_3_** APIs):
- **PUT** `/api/profile/:id`
- **GET** `/api/profile/:id`
- **GET** `/api/profile/private/:id`

### What I propose (feel free to propose different APIs - around **_40_** APIs):
> **POST** is used to override what is there with the content passed to the API and **PUT** updates the content and merges it

#### Generic profile information
- **POST** `/api/profile` (getting rid of the `user` API)
- **DELETE** `/api/profile/:id` (getting rid of the `user` API)
- **PUT** `/api/profile/:id` (patches the values strictly belonging to the profile table)
- **GET** `/api/profile/:id` (gets the values strictly belonging to the profile table (which includes foreign ids to other tables))

#### Foreign ids of profile
- actingLevel
- careerMobility
- classification (groupLevel)
- lookingJob
- officeLocation
- securityClearance
- talentMatrixResult
- tenure

We would have similar APIs
- **POST** `/api/profile/{name}/:id`
- **DELETE** `/api/profile/{name}`

#### Visibility cards
- **PUT** `/api/profile/visibility`
- **GET** `/api/profile/visibility`

> **Note:** for the following I'm not sure about the **DELETE**

#### For each of the following
- competencies
- developmentalGoals
- educations
- experiences
- mentorshipSkills
- qualifiedPools
- relocationLocations
- secondLangProfs
- skills

We would have similar APIs
- **GET** `/api/profile/{name}`
- **PUT** `/api/profile/{name}` (with the ids in the body)

**Comment by BenJeau** [comment]
My software architecture course that I'm currently taking made me more aware of this, that we are not using fully one of the software architecture for the backend.

This is why when we revamped the backend, the way we handled the "options" in the backend changed a lot, for it to be modularized, less coupled, which makes it look less like "magic" and more understandable

**Comment by mo-5** [comment]
Closing this as per the discussion I had with Ali a while back. This change will be large and may introduce a lot of bugs in the application.
