### ISSUE TITLE
Backend Security Hotspot (SonarQube)

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1052]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/98294125-68874280-1f7d-11eb-9774-f2fd1b2f4291.png)

**Additional context**

**Comment by BenJeau** [comment]
These are cors related, I think they are fine, but I assigned them on SonarQube to @dynamic11 since he was doing the node.js security checklist.

**Comment by Mousto097** [comment]
Will not be able to work on this issue by the end of term!

**Comment by MenaMachado** [comment]
@MohamedRadwan , can you review status
