### ISSUE TITLE
Profile Not found on dev

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1053]
**Describe the bug**
I noticed this on dev and only occurs with one person. I am not sure how it was produced and if it is reoccurring. Might be worth looking into before prod.
**To Reproduce**
Go to Nora Dorogi's profile from admin dashboard. 

**Expected behavior**

**Screenshots**
1. click on their profile 
![image](https://user-images.githubusercontent.com/21133129/98294674-56f26a80-1f7e-11eb-8f37-4795fdf4d985.png)
2. get a profile not found error 
![image](https://user-images.githubusercontent.com/21133129/98294694-5ce84b80-1f7e-11eb-914a-7a4c664504de.png)

**Additional context**

**Comment by mo-5** [comment]
Note: I think I know where this issue is coming from. After filling out my profile I am unable to visit my profile take a look at the screenshot below. 

![image](https://user-images.githubusercontent.com/21133129/98295381-82298980-1f7f-11eb-9eb7-06995e260503.png)


I think this is related to #1042

**Comment by BenJeau** [comment]
I think this bug is the same as #1043, @MohamedRadwan can you verify if its the same?

**Comment by mo-5** [comment]
> I think this bug is the same as #1043, @MohamedRadwan can you verify if its the same?

Yes you are right I will close this issue
