### ISSUE TITLE
Update OpenShift template for prod

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#1058]
To be ready for prod, our OpenShift template must be up to date. 

Here are few of my questions, regarding the current one, to know what is important and what should be inside of it.
1. Should OpenShift have a PostgreSQL database? - I think the answer is no, but want to make sure
2. Should OpenShift have a Redis database? - I'm not sure, I think this depends if the OpenShift projects gets overwritten all the time, so it would clear the sessions when updating prod (this would be a question for Derek)
3. Should the template contain secrets? - I don't think so, but then again not sure how the prod process is

@MohamedRadwan what do you think about the first one and the maybe the second one

**Comment by mo-5** [comment]
> Should OpenShift have a PostgreSQL database? - I think the answer is no, but want to make sure

I added the database secret for UAT in openshift so it's just a matter of changing the env variable and running the migrations and seeds. 

>Should OpenShift have a Redis database? - I'm not sure, I think this depends if the OpenShift projects gets overwritten all the time, so it would clear the sessions when updating prod (this would be a question for Derek)

I am not entirely sure how redis works but if we can create a Postgres SQL for it let me know I could create one and add the connection string to the application.

**Comment by BenJeau** [comment]
Okk, thank you for the response, I'll remove the PostgreSQL pod from the template. Redis is its own type of database. I think for now I'll keep it in the OpenShift template, as I don't see any "major" problems other than the sessions not persisting when promoting prod, if the OpenShift instance gets destroyed everytime (which I don't think will happen)

**Comment by mo-5** [comment]
Can you also remove the PostgresSQL from dev template?

**Comment by BenJeau** [comment]
Yepp, since uat, dev and prod now use the same architecture (in the past uat didn't have redis) they are now using the same template

**Comment by MohamedRadwan** [comment]
related to  #1025

**Comment by mo-5** [comment]
UAT template is now up to date
