### ISSUE TITLE
nav profile button dropdown closes as soon as its expanded

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1069]
**Describe the bug**
nav profile button dropdown closes automatically as soon as its expanded

**To Reproduce**
1. Go to 'profile page'
2. Click on 'profile dropdown in navbar'
4. See dropdown open and automatically close
* after first try it starts to work as expected

**Expected behavior**
it should remain open

**Screenshots**
![profileDropdown](https://user-images.githubusercontent.com/11470442/99088631-494e6d80-259a-11eb-9a1d-b79c967afb3a.gif)

**Comment by BenJeau** [comment]
Can't seem to replicate on dev (I'm on Firefox)

![Peek 2020-11-14 23-35](https://user-images.githubusercontent.com/22248828/99163020-16a79080-26d2-11eb-9a02-e14019e27ef3.gif)

**Comment by dynamic11** [comment]
@BenJeau i noticed that it only happens when dev tools is open. 🕵️

**Comment by BenJeau** [comment]
@dynamic11 I just tried it on chrome with the inspect element and don't see it happening? mhh should we close it?

![Peek 2020-11-15 12-52](https://user-images.githubusercontent.com/22248828/99192570-82751200-2741-11eb-8e18-aa1d7a9d3393.gif)

**Comment by dynamic11** [comment]
looks like the issue is local to me

**Comment by mo-5** [comment]
Looks like to only happening on Chrome mobile simulation in dev tools (issue is happening with iPad pro setting)

**Comment by BenJeau** [comment]
Just tried it on my iPad, I don't see this problem on Safari or Chrome (but I don't have the pro)

**Comment by mo-5** [comment]
oh sorry I meant enabling this setting in the chrome dev tools 
![image](https://user-images.githubusercontent.com/21133129/99210708-80886e80-2794-11eb-9cf5-172db7f17b84.png)
![image](https://user-images.githubusercontent.com/21133129/99210700-7b2b2400-2794-11eb-88fb-958568802ca8.png)

it simulates an iPad and the issue occurs with it

**Comment by BenJeau** [comment]
I just mentionned that since I don't think we should worry if it works on an actual device (the same "bug" happens when selecting the iPad from that view, so I think if it works on a real iPad, it should be fine?)
