### ISSUE TITLE
ON HOLD: Add axe-core testing on the application

### ISSUE THREAD

**Issue by SukhsimranpreetSekhon** [CDH-Studio/UpSkill#1071]
**Is your feature request related to a problem? Please describe.**
- Ali brought up a useful idea to have accessibility testing on the application for future use and help keep a standard of accessibility for the application.

**Describe the solution you'd like**
- Use axe-core npm to setup testing
- Unsure if it would work on GitHub as another test when submitting PR's.

**Describe alternatives you've considered**

**Additional context**
https://www.npmjs.com/package/axe-core

**Comment by Rizvida1** [comment]
Axe-core is a library that shows any new accessibility issues as you develop new components. This is useful when there are no accessibility issues when you start developing so it isn't worth implementing at the moment. 
Currently, we should use Chrome extensions such as [axe DevTools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?gl=DK&hl=en).
Later on, we can integrate accessibility testing into the CI process using libraries such as cypress-axe.

**Comment by MenaMachado** [comment]
Agree with Rizvi's comment. Therefore let's close this issue
