### ISSUE TITLE
GEDS cannot fetch my profile

### ISSUE THREAD

**Issue by Mousto097** [CDH-Studio/UpSkill#1075]
**Describe the bug**
When logging in the app for the first time, I cannot create a profile using GEDS and the GEDS button is loading indefinitely (no timeout).

**To Reproduce**
1. Go to the Sign in Page and Log in using your credentials
2. Click on "Fetching profiles from GCdirectory" when redirected to the Setup Page
3. See that GEDS search will load indefinitly....

**Expected behavior**

1. GEDS should return my profile and autofill the organization and contact information.
2. GEDS search needs to timeout if it cannot find the profile after a while.

**Screenshots**
<img width="1278" alt="Screen Shot 2020-11-13 at 5 10 05 PM" src="https://user-images.githubusercontent.com/29315512/99125915-1d9ba980-25d3-11eb-8bca-9201d5db8c1b.png">

**Additional context**
Sukhu and Mamadou are both experiencing this issue.

**Comment by BenJeau** [comment]
Seems like they changed their API endpoints? This is the log in OpenShift
![image](https://user-images.githubusercontent.com/22248828/99193848-991f6700-2749-11eb-8ecb-da65d802d1c3.png)
