### ISSUE TITLE
The bottom of the side nav bar is overflowing with no scroll option

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#1092]
![image](https://user-images.githubusercontent.com/49656364/99447305-2e0e9580-28ed-11eb-9ffa-af27f4515310.png)

**Comment by dynamic11** [comment]
I am working on this as we speak!

**some helpful code for future ali:**
https://github.com/ant-design/ant-design/issues/6997#issuecomment-557597006
