### ISSUE TITLE
Switch the footer links to Modal instead of a new page 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1098]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BenJeau** [comment]
I agree with you, but I'm not sure if it would be a "waste of time" if we are gonna use Drupal for those links in the future. @dynamic11 how's Drupal coming along? Do you think it could be rendered inside of a modal?

**Comment by mo-5** [comment]
yea you are right I forgot about Drupal. I will leave it as is for now then
