### ISSUE TITLE
Description styling 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1102]
**Describe the bug**
Once the user clicks on expand description it should open downwards not upwards. What do you guys think ? 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/100251555-e602fa80-2f0c-11eb-8281-d78b9a638578.png)

**Additional context**

**Comment by dynamic11** [comment]
i agree with this. i find it odd
