### ISSUE TITLE
Correct translation for "EX-Feeder"

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#1104]
I just noticed that we did not translate EX-Feeder on the French version. 

The French translation for EX-Feeder should be "Group de relève"

**Comment by BenJeau** [comment]
Just talked to Mena, it should be "EX Feeder" in English and "Relève des EX" in French

**Comment by MenaMachado** [comment]
I checked our HR intranet site to confirm. It's written in different ways depending on the context in French. EX Feeder groups translates to groupes de relève des EX.  We're not using the word groups in english so I took out "groupes de"
