### ISSUE TITLE
"users" page in admin dash crashs

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1179]
**Describe the bug**
I experience this in local dev. when I go to the "users" page in the admin dash it crashes. Seems like backend is returning a 500 error. @MohamedRadwan are you also seeing this?

**To Reproduce**
1. Go to admin dash
2. Click on users in side nav

**Expected behavior**
it show table of all users

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/103165126-de6f9380-47e1-11eb-8ab6-aba8066f2609.png)

**Comment by mo-5** [comment]
it's working for me. It might a one-time keycloak issue.
