### ISSUE TITLE
Update prisma to 2.23 or latest 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1186]
This update has a lot of breaking changes but also they fixed a lot of errors. We should update to the latest. Please take a look at this https://github.com/prisma/prisma/releases for all the breaking changes

**Comment by mo-5** [comment]
before going to prod we should update to the latest in case we need to wipe the database or migrations.

**Comment by MenaMachado** [comment]
Prisma is constantly updating which is causing issues when it updates
