### ISSUE TITLE
Invalid prop `data.organizations[0]`

### ISSUE THREAD

**Issue by Mousto097** [CDH-Studio/UpSkill#1192]
**Describe the bug**
Proptype error for "data.organizations[0]" in profile page

**To Reproduce**
1. Go to profile page
2. refresh page
3. see error in console

**Expected behavior**
there should be no error

**Screenshots**
<img width="1276" alt="Screen Shot 2020-12-28 at 7 26 21 PM" src="https://user-images.githubusercontent.com/29315512/103250677-104c3b80-4943-11eb-992a-e0a7bf6d92d0.png">

**Comment by MenaMachado** [comment]
Try to recreate and if not able, close ticket

**Comment by Rizvida1** [comment]
Unable to recreate issue
