### ISSUE TITLE
Unable to setup Docker on Image Device (ISED issued laptops)

### ISSUE THREAD

**Issue by ianwilk20** [CDH-Studio/UpSkill#1204]
@dynamic11 said that new employees with Image Devices were unsuccessful in using Docker, due to the proxy that these Image Devices must connect to.

To Do:
- A Step-by-Step guide

**Comment by P4ul1029** [comment]
After investigating the issue further, it appears WSL 2 has compatibility issues with Cisco Anyconnect and WSL 1 is not compatible with Docker Desktop. Next step would be to attempt setting up the enviroment using Docker Hyper-V instead of WSL 2.
