### ISSUE TITLE
Add Siteimprove Analytics to I-Talent for web analytics

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#1228]
Siteimprove, is ISED’s new enterprise-level web analytic. We need to add Siteimprove analytics to I-Talent. 

I'm reaching out to some contacts at ISED for the process we need to follow for adding it to our site. 

In the meantime, I found this:  
https://support.siteimprove.com/hc/en-gb/articles/206343703

here is the script that we were provided: 
[siteimprove-tracking-code.txt](https://github.com/CDH-Studio/I-Talent/files/5946930/siteimprove-tracking-code.txt)

**Comment by dynamic11** [comment]
I started this
and im preparing a PR

**Comment by MenaMachado** [comment]
Was overwritten and needs to be redone.
