### ISSUE TITLE
In Experience Section Remove Requirement for providing "Reference Letter" in drop down list

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#1302]
Given a user is in Edit Profile, Experience Section
When they select "Attachment Links"
Then they will be presented 2 options: Awards and Recognition, and Work Sample
They must no longer be able to provide a reference letter

Task:
Remove Reference Letter from drop down list. 

![image](https://user-images.githubusercontent.com/49656364/114954628-01719200-9e29-11eb-87c6-e06093172253.png)

**Comment by mo-5** [comment]
reopening this issue because there was an issue when it was merged. I will wait for the Prisma update so we can clean up our seeds

**Comment by mo-5** [comment]
This is complete
