### ISSUE TITLE
Issue with Jenkins builds

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#1365]

**Comment by mo-5** [comment]
The current issue with this Jenkins is that it gets stuck when it loads the prisma table to run the testing for the backend. 

![image](https://user-images.githubusercontent.com/21133129/118669390-b3eb9a80-b7c3-11eb-86d1-5064725d8a9b.png)

**Comment by MenaMachado** [comment]
Issue resolved
