### ISSUE TITLE
Admin Dashboard, User Table - Create a separate colunm to identify hidden profiles

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#1463]
A user can set their profile to hidden. When they do, the status in the users table appears as hidden.  The status column has 2 options for an Admin: Active/Inactive. If an Admin sets the profile to Inactive, the profile no longer appears in search results. Only the user and Admin can see it.  There is no "hidden" option for an Admin. Therefore it can be confusing. 

It would be better to have a separate column  to identify which user profiles that have been hidden by the user. 

![image](https://user-images.githubusercontent.com/49656364/121744611-256fed80-cad1-11eb-9802-69627d354712.png)

![image](https://user-images.githubusercontent.com/49656364/121744911-99aa9100-cad1-11eb-8109-1ce5a4ef87d2.png)

**Comment by mo-5** [comment]
Hi @MenaMachado, I was going to start this ticket and had a question. So lets say someone set their profile to hidden what should an admin see ? 

would there be a column that says "hidden" and then another common for [active, inactive] ? if so what should be displayed in the active/inactive column ?

**Comment by MenaMachado** [comment]
Hi Mohamed

I hope I can clarify.

Profile status perhaps can remain as is where the Admin can change the status from Inactive to Active at any time. If it’s inactive, it’s no longer searchable.

There should be a new column added. Maybe we can call the column “Hidden by user” and a radio button is solid when hidden.

What do you think?

**Comment by MenaMachado** [comment]
Create the heading called " Visibility" and use the eye for not hidden and eye crossed out for hidden
