### ISSUE TITLE
Official languages save fails

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1470]
**Describe the bug**
If you fill in the language form as in the screenshot and try to save you will see it fail to save with strange error

![image](https://user-images.githubusercontent.com/11470442/122281495-52007c80-ceb8-11eb-8d90-fe0b608fa0cf.png)

**Comment by MenaMachado** [comment]
Remove "valid" from the question - Do you have valid SL results? and make the status a requirement

**Comment by dynamic11** [comment]
it has not been resolved
