### ISSUE TITLE
check how screen reader behaves with the implemented notification pop ins

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1491]
**Describe the bug**
screen reader should read the popins

**To Reproduce**

1. Go to profile
2. chnage visibility of one of the cards
3. see if screen reader reads the success message

**Expected behavior**
It should get interrupted and read the message

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/122811403-6f5d8e00-d29e-11eb-8d20-8016a53909db.png)

**Comment by MenaMachado** [comment]
Ali has looked into it, it appeared fine but didn't check all

**Comment by Rizvida1** [comment]
It works as expected
