### ISSUE TITLE
The username urls are not being saved correctly 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1518]
**Describe the bug**
Urls are not being saved correctly 

![image](https://user-images.githubusercontent.com/21133129/124011250-cefa1e80-d9ad-11eb-951c-dfb403ac71c6.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dynamic11** [comment]
Is this the issue I was worried about?

**Comment by mo-5** [comment]
> Is this the issue I was worried about?

Yes, I think it's the same issue. It shouldn't be too bad to fix I will look into it

**Comment by dynamic11** [comment]
i'm looking into this

**Comment by dynamic11** [comment]
I noticed that it doesn't see the unsaved changes
![image](https://user-images.githubusercontent.com/11470442/124627539-a3fc4880-de4d-11eb-96f9-0f8a6fb2f176.png)

**Comment by dynamic11** [comment]
This was definitely caused by me....... I think I know how to fix it.
