### ISSUE TITLE
"Experience" form label too long 

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1529]
**Describe the bug**
I believe there was mistake when the translations were reviewed all instances of the word "experience" was changed to "Experience (starting with most recent)". This does not work every where.
 

**Expected behavior**
It should just say experience

**Screenshots**
![124521109-6bf8f500-ddbc-11eb-961d-8ef23a640102](https://user-images.githubusercontent.com/11470442/128365588-0bcc9532-14ee-4da7-a77c-3311381d448b.png)

**Comment by MenaMachado** [comment]
only keep the one in the middle the others should be Experience only
