### ISSUE TITLE
Backend optimization 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1531]
**Describe the bug**
skills and locations take a long time to get retrieved its not really a big issue I thought it was something we should look at. 

Upon further investigation I found the cause for this 
![image](https://user-images.githubusercontent.com/21133129/124547447-22c79600-ddfa-11eb-9342-d1d9943aaed9.png)

these function cause a total of O(2*n) time complexity.  Which makes sense and probably the reason why we have such high numbers. I will look into reducing it to O(n)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/124546885-4807d480-ddf9-11eb-8396-50744c2c188d.png)
![image](https://user-images.githubusercontent.com/21133129/124546907-5229d300-ddf9-11eb-98a3-82be1bce9112.png)
![image](https://user-images.githubusercontent.com/21133129/124548648-ff054f80-ddfb-11eb-8d19-5bfbc83dc480.png)

**Additional context**

**Comment by MenaMachado** [comment]
Improve endpoints
