### ISSUE TITLE
Add label for Second Language Results  

### ISSUE THREAD

**Issue by Rizvida1** [CDH-Studio/UpSkill#1534]
**Describe the bug**
Might be worth adding a label saying that these are the second language result. Seems unclear otherwise.

**Screenshots**
![image](https://user-images.githubusercontent.com/31704878/124644907-c51a6480-de60-11eb-9859-4774a37681c2.png)

**Comment by MenaMachado** [comment]
Secondary language label can be above results as "Second Language Results"
