### ISSUE TITLE
[Accessibility Bug] Privacy Agreement Read Aloud Twice

### ISSUE THREAD

**Issue by AminaSalah** [CDH-Studio/UpSkill#1545]
**Describe the bug**
Privacy Agreement Modal:
NVDA reads "Privacy Agreement" twice in a row after logging in when the page loads and the modal is present. This is not an uncommon issue, but if it can be avoided that would be optimal.

**Expected behavior**
"Privacy Agreement" is not unnecessarily repeated by the screen reader.

**Comment by MenaMachado** [comment]
It's likely an Ant design issue. The way it generates the component. It reads the labels twice.

**Comment by Rizvida1** [comment]
As Mena commented above, it is an Antd modal issue. The dialog for the title is aria-labelled-by the title itself which causes it to be read twice and can't be changed by us because it is within the Antd code.
