### ISSUE TITLE
link to "contact us" in footer and "profile inactive message" is broken

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1607]
**Describe the bug**
the "contact us" link is broken

**To Reproduce**

1. Go to any page
2. Click on 'contact us' in the footer
3. See error

**Expected behavior**
it should redirect to the wiki

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/128890361-4432ff0e-e7a5-4965-813f-af57583099d1.png)
![image](https://user-images.githubusercontent.com/11470442/128890424-320f5510-7ef6-4906-8c63-eaf772c41eef.png)

**Comment by dynamic11** [comment]
@mo-5 is this becasue i dont have it configured in my env file?

**Comment by mo-5** [comment]
Yeah I think its a configuration issue ? Is this happening on all the druapl links like about, terms and conditions ?

**Comment by dynamic11** [comment]
yes. I guess I can just close this since its not really an issues.
