### ISSUE TITLE
console error on education form

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1615]
**Describe the bug**
please see screenshot

**To Reproduce**

1. Go to 'education form.'
2. open console 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/129210187-d57b5316-bd6a-42dd-96fc-36606cd80237.png)

**Comment by P4ul1029** [comment]
The same error is present on the Experience form. I'll create a fix for both.
![14](https://user-images.githubusercontent.com/46769064/134920909-97f1c948-f0ec-4a63-a90a-9f5da47ef45d.JPG)
