### ISSUE TITLE
"clear changes" takes form state to original "on page load state"

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1644]
**Describe the bug**
the "clear changes" button takes the form's state to original "on page load state" rather than "last saved" state. This effects every form!

**To Reproduce**

1. Go to 'primary info form'
2. set location to "235 Queen"
3. reload the page
4. change location to "56 sparks street"
5. hit "save"
6. change the location again to any other option
7. hit "clear changes"
8. see the location return to "235 Queen" when it should be the last save state "56 sparks street"

**Expected behavior**
it should return the form state to the last saved values

**Comment by MenaMachado** [comment]
to fix:
reload the page on save but you get a jarring refresh
