### ISSUE TITLE
Add a filter at the top of each Table in Admin Dashboard for HR Admin Users

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#304]
As an HR Admin User, in each table, it's currently not possible to search for a specific User, Category, Skill, Competency, Diploma or School in the Admin Dashboard pages. For each table, eg. category, you need to scroll through them all to find a specific category. If you want to add a new category, you will need to confirm first if the category already exists in the system and without a filter, this can be time consuming. 

The solution:
Add a filter at the top of each page (perhaps next to the header) for each of the following tables:

Users
Categories
Skills
Competencies
Diplomas
Schools

Example 
![image](https://user-images.githubusercontent.com/49656364/83065157-feaf5800-a030-11ea-97e5-555ead5f90ef.png)

**Comment by BenJeau** [comment]
![szoter_annotated_image](https://user-images.githubusercontent.com/22248828/83297716-13225a80-a1c1-11ea-9954-a8dd9c63675b.jpeg)

They can search by field in tables right now like shown in the above screenshot. Is that good enough or do we want a global search for the table?

**Comment by MenaMachado** [comment]
Hi Ben

I didn’t notice the search field!

You can cancel this issue. It’s perfect as is.

On May 29, 2020, at 3:33 PM, Benoît Jeaurond <notifications@github.com> wrote:

﻿

[szoter_annotated_image]<https://user-images.githubusercontent.com/22248828/83297716-13225a80-a1c1-11ea-9954-a8dd9c63675b.jpeg>

They can search by field in tables right now like shown in the above screenshot. Is that good enough or do we want a global search for the table?
