### ISSUE TITLE
Replace Moment js  with Day.js

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#883]
**Is your feature request related to a problem? Please describe.**
Moment js is a very large package. This will cause slowdowns in the frontend for the package to have to load from scratch. I think we should look into using another package like day js 

https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BenJeau** [comment]
I think this is integrated in ant design, but it seems doable to change to something else than moment.js https://ant.design/docs/react/replace-moment
