### ISSUE TITLE
Rename Project UpSkill --> ITalent

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#916]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dynamic11** [comment]
@BenJeau can we have a meeting about this? we need to sync it with the branch change (master to development)

**Comment by BenJeau** [comment]
We also *may* be able to rename our project in openshift, https://access.redhat.com/solutions/1982113

**Comment by dynamic11** [comment]
done
