### ISSUE TITLE
Test Screen Reader Compatibility with NVDA

### ISSUE THREAD

**Issue by MenaMachado** [CDH-Studio/UpSkill#922]
Find this app here for free: 

https://www.nvaccess.org/download

This tool enjoys wide usage and a large community of support behind it, as well as a comprehensive list of controls and settings that users generally don’t have to even look at.
TIP: change the reader’s “mode” by holding ‘caps lock’ and hitting ‘spacebar’. This manual mode change can make it clear to testers what the reader is trying to do at any given moment.

![image](https://user-images.githubusercontent.com/49656364/94704396-dd77b480-030d-11eb-81d1-39f827f87d22.png)

Testing process for Screen Readers:
1.	Launch the app or website to be tested
2.	Initialize the screen reader
3.	If on PC, abandon the mouse; using only keyboard/touchscreen and screen reader combination, attempt to perform the regular workflows of the application in question:
a.	Is it clear where the user is at all times?
b.	Is it clear what each on-screen element does?
c.	Is it clear where the user can go next / what their options are?
d.	If an element is important for the workflow, is its function and state conveyed to the user?
e.	Etc.
4.	Take particular note of any situations in which the user is even mildly confused about literally any part of the app at all. User confusion – for both sighted and sightless users – will lead to frustration and the user with assistive tech may not return to the application.

**Comment by SukhsimranpreetSekhon** [comment]
Going to report issues with the screen reader separate for each page and get them fixed for launch.
