### ISSUE TITLE
Sync GCdirectory data btn returns server error in backend

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#925]
**Describe the bug**
Sync GCdirectory data btn returns server error in backend

**To Reproduce**
1. Go to 'edit profile'
2. Click on "sync GCdirecotry data"
3. See error in console

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/94739704-5fcc9c80-033f-11eb-9c84-f1492946f72f.png)

**Additional context**

**Comment by dynamic11** [comment]
I see this. I believe it is related to Redis:

![image](https://user-images.githubusercontent.com/11470442/94740271-5b54b380-0340-11eb-8c76-de8e7651e804.png)

**Comment by BenJeau** [comment]
I never got this error before, and seems like a local issue, are you able to reproduce it within OpenShift?

**Comment by dynamic11** [comment]
> I never got this error before, and seems like a local issue, are you able to reproduce it within OpenShift?

identified the problem. working on a fix.

**Comment by BenJeau** [comment]
I'm curious as to what the problem is, could you briefly mention the cause?

**Comment by BenJeau** [comment]
I get the same thing locally  - does not seemt to be happening on Openshift, but seems related to rolling keys or something like that for cookies
