### ISSUE TITLE
Start/End date is not working in profile form

### ISSUE THREAD

**Issue by Mousto097** [CDH-Studio/UpSkill#931]
**Describe the bug**

The app is crashing when trying to add a 'Start date' or 'End date' to profile 'Education' or 'Experience' section.

**To Reproduce**
1. Go to https://italent-development.apps.dev.openshift.ised-isde.canada.ca/
2. Go to your Education section in your profile (**add an Education item if you do not have one)
3. Click on 'Start date' or 'End date' on the education form (** in Edit mode)
4. The entire application will crash

Note: Same issue with the Experience section.

**Expected behavior**
A calendar should pop up and user should be able to choose a 'Start date' or 'End date'

**Screenshots**
N/A

**Additional context**

This bug might be related to https://github.com/CDH-Studio/I-Talent/issues/883

**Comment by BenJeau** [comment]
This bug is related to day.js https://github.com/CDH-Studio/I-Talent/issues/883 (I think)

**Comment by BenJeau** [comment]
Seems like the same error https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/36
