### ISSUE TITLE
Move from Bizcharts to Chartjs-2

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#950]
**Is your feature request related to a problem? Please describe.**
Bizcharts documentation is all in Mandarin and may the charts part of our code may not be well understood by maintainers later on... I just saw that the covid19 Ontario website is using ant design for the table and ApexCharts for its charts. At least their docs are in english and the design is not that bad

**Describe the solution you'd like**
We should probably move to ApexCharts https://github.com/apexcharts/react-apexcharts

**Additional context**
You can see which library they use by looking at the source code of the website

https://covid-19.ontario.ca/data

**Comment by SukhsimranpreetSekhon** [comment]
@BenJeau I can take a look at this after launch and work on it for sure. The reason I made those graphs in Admin using Bizcharts was because of Alibaba supporting it. I used the google translate page function in Chrome to understand everything (it translated easily).

**Comment by BenJeau** [comment]
@SukhsimranpreetSekhon yeah I did the same to translate the docs / API page, but I'm not sure if the maintainers would like to do that. I think this is something that can be done after the first prod release - @dynamic11 what do you think?

**Comment by dynamic11** [comment]
I'm all for well supported libraries so as long as apex is well supported then I see no problems

**Comment by mo-5** [comment]
Moving to Chartjs-2 since its a smaller module
