### ISSUE TITLE
Prisma Migrations failing since upgrade from 2.7.1 (client & CLI)

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#952]
**Describe the bug**
- running docker from scratch doesn't work anymore. backend keeps crashing when it goes to migrate. The issue seems to be resolved when I delete our migrations directory and start it from scratch using `yarn migrate:create`.

- from my understanding the issues is due to one of the commands in the migrations causing an error in postgres. This causes the CLI to crash.

- according to PRISMA documentation some of these issues can be resolved by nuking the migrations folder and starting again:
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-migrate

potentially related issue:
https://github.com/prisma/prisma/issues/3805

**Error:**
  There will be data loss:

-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will add a unique constraint covering the columns `[userId,relocationLocationId]` on the table `RelocationLocation`. If there are existing duplicate values, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will add a unique constraint covering the columns `[userId,relocationLocationId]` on the table `RelocationLocation`. If there are existing duplicate values, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will add a unique constraint covering the columns `[userId,relocationLocationId]` on the table `RelocationLocation`. If there are existing duplicate values, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will add a unique constraint covering the columns `[userId,relocationLocationId]` on the table `RelocationLocation`. If there are existing duplicate values, the migration will fail.
-  The migration will remove the values [FRIENDS] on the enum `CardVisibilityStatus`. If these variants are still used in the database, the migration will fail.
-  The migration will add a unique constraint covering the columns `[userId,relocationLocationId]` on the table `RelocationLocation`. If there are existing duplicate values, the migration will fail.

**Comment by dynamic11** [comment]
will temporarily revert the CLI and the client to 2.7.1 until a fix is provided by Prisma for the following: 
prisma/prisma#3805

**Comment by dynamic11** [comment]
- Prisma CLI and Client >2.7.1 caused the migrations to fail.
- We either had to delete all migrations and generate a new one from scratch or rollback until a fix is introduced.
- nuking the existing migrations may cause issues in the live DBs. For this reason we will rollback to 2.7.1 until a fix is introduced

**Comment by BenJeau** [comment]
Technically not fixed, since prisma is still @2.7.1. Instead of opening a new issue on upgrading to the newest prisma, I think we should link it to this one
