### ISSUE TITLE
Feedback from users

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#959]
**Is your feature request related to a problem? Please describe.**
Adding a small feedback system in the application could be beneficial, when the user wants to report a bug or has some suggestions for the application

**Describe the solution you'd like**
Somewhere to put some text like a comment (maybe in the footer, or in the dropdown, or on the logged in home page), it would automatically link the comment to that user, we would see it in the admin dashboard and we could triage it later on

**Comment by mo-5** [comment]
I agree with this. I think we should also look at the following:
- We should also include the version number so that we know which version the user is running.
- Add a changelog so that they know if the issues have been resolved

**Comment by BenJeau** [comment]
Technically now with the new promoting process in Jenkins, it creates github releases. So we can easily modify its name/description (we can easily add a changelog there), but I'm not sure how we would get the version in the application. 

I have an idea, but it doesn't feel like the best one. We could query the GitHub API to get the latest release id, but this would suppose that what is on the servers is always pointing to the latest release.

There must be a better way to do this...
