### ISSUE TITLE
Backend Code duplication 

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#968]
Please take a look at the code duplication found here: https://sonarqube-ised-ci.apps.dev.openshift.ised-isde.canada.ca/component_measures?id=ITalent-backend&metric=duplicated_lines_density&view=list

**Comment by BenJeau** [comment]
A lot of it are database related files, 

![image](https://user-images.githubusercontent.com/22248828/98182560-13432680-1ed4-11eb-8b04-514f64a8b4e6.png)

**Comment by BenJeau** [comment]
I think we can close this issue now @MohamedRadwan / @dynamic11 ? We were at 40% before
![image](https://user-images.githubusercontent.com/22248828/99195355-24512a80-2753-11eb-9078-6dcbb92c8af6.png)
![image](https://user-images.githubusercontent.com/22248828/99195393-58c4e680-2753-11eb-9864-488e9b7fdf87.png)
