### ISSUE TITLE
Switch from craco to neutrinos.js

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#991]
**Is your feature request related to a problem? Please describe.**
I'm not sure how I didn't see this before, but react themselves recommend neutrino.js in their [README](https://github.com/facebook/create-react-app#whats-included). We should switch to it, since it does not rely on `react-scripts` and it will be less finicky updating our frontend packages. In addition, I'm not even sure if `craco` will support the latest version of `react-scripts`

**Describe the solution you'd like**
Switch to neutrino.js

**Describe alternatives you've considered**
We've tried `react-app-rewired` with `customized-cra` in the past, then switched to `razzle.js`, and now we are using `craco`.

**Additional context**
https://github.com/gsoft-inc/craco/issues/205

**Comment by mo-5** [comment]
If this improves the overall application maybe we should move it to a priority depending on how long it would take to implement?

**Comment by BenJeau** [comment]
Its hard to estimate... Creating a new project with neturino.js with react is rather easy, but with our webpack plugins/ant design not sure. I'll give it an hour or so, and see what I've done
