### ISSUE TITLE
Use scoped styling files

### ISSUE THREAD

**Issue by BenJeau** [CDH-Studio/UpSkill#995]
**Is your feature request related to a problem? Please describe.**
Since evey styling files are included when loading any page, the class names can overlap and override each other. 

**Describe the solution you'd like**
To use `react-scoped-css` to prevent having the need of prepending something unique to the class names for each components. There's a craco plugin for it https://github.com/gaoxiaoliangz/react-scoped-css

**Describe alternatives you've considered**
Keep prepending something unique to the class names (which is not ideal)

**Additional context**
NA

**Comment by BenJeau** [comment]
We should just utilize the nested scss/less feature maybe instead of adding a new dependency.

Ex:

```scss
.lang-header {}
.lang-title {}
.lang-buttonContainer {}
```

to

```scss
.lang {
  &-header {}
  &-title {}
  &-buttonContainer {}
}
```

**Comment by mo-5** [comment]
Since the application has been moved to scss/less I will close this issue
